In [20]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [21]:
traffic_data= pd.read_csv("train.csv")
test_data= pd.read_csv("test.csv")
traffic_data.head()

A1  A2  A3  A4  PrestateA1  PrestateA2  PrestateA3  PrestateA4  BacknodeA1  \
0   1   2   3   4           0           0           0           0           0   
1   1   2   4   3           0           0           0           0           0   
2   1   3   2   4           0           0           0           0           0   
3   1   3   4   2           0           0           0           0           0   
4   1   4   2   3           0           0           0           0           0   

   BacknodeA2  BacknodeA3  BacknodeA4 Light  
0           0           0           0    A1  
1           0           0           0    A1  
2           0           0           0    A1  
3           0           0           0    A1  
4           0           0           0    A1

In [22]:
traffic_data.shape

(393, 13)

In [23]:
traffic_data['Light'] = traffic_data['light'].apply(str)

test_data['Light'] = test_data['Light'].apply(str)

print (traffic_data.dtypes)

KeyError: 'light'

In [16]:
X_trainset=traffic_data[['Road1','Road2','Road3','Road4']].values

X_testset=test_data[['Road1','Road2','Road3','Road4']].values

y_trainset=traffic_data['Output']

y_testset=test_data['Output']


KeyError: "None of [Index(['Road1', 'Road2', 'Road3', 'Road4'], dtype='object')] are in the [columns]"

In [17]:
#from sklearn.model_selection import train_test_split

In [ ]:
#X_trainset,X_testset,y_trainset,y_testset=train_test_split(X,y,test_size=.3,random_state=3)

# Dicision tree

In [ ]:

trafficTree = DecisionTreeClassifier(criterion='entropy',max_depth=3 )

trafficTree

In [ ]:
trafficTree.fit(X_trainset,y_trainset)

In [4]:
ytree=trafficTree.predict(X_testset)

NameError: name 'trafficTree' is not defined

In [5]:
print (ytree [0:5])
print (y_testset [0:5])


NameError: name 'ytree' is not defined

In [6]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("Dicision accuracy",metrics.accuracy_score(y_testset,predTree))

NameError: name 'y_testset' is not defined

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_testset,predTree))

In [7]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_testset,ytree)

NameError: name 'y_testset' is not defined

# KNN

In [175]:
k = 1

neigh = KNeighborsClassifier(n_neighbors = k).fit(X_trainset,y_trainset)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [176]:
yKNN = neigh.predict(X_testset)
print(yKNN[0:5])
print (y_testset [0:5])

['3421' '1324' '2413' '2431' '3142']
0    4321
1    1234
2    2413
3    2431
4    3142
Name: Output, dtype: object


In [177]:
from sklearn.metrics import classification_report
print(classification_report(y_testset,yKNN))

              precision    recall  f1-score   support

        1234       0.00      0.00      0.00         1
        1324       0.00      0.00      0.00         0
        2413       1.00      1.00      1.00         1
        2431       1.00      1.00      1.00         1
        3142       1.00      1.00      1.00         1
        3214       1.00      1.00      1.00         1
        3241       1.00      1.00      1.00         1
        3421       0.00      0.00      0.00         0
        4213       1.00      1.00      1.00         1
        4231       1.00      1.00      1.00         1
        4312       1.00      1.00      1.00         1
        4321       0.00      0.00      0.00         1

    accuracy                           0.80        10
   macro avg       0.67      0.67      0.67        10
weighted avg       0.80      0.80      0.80        10



K:\anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
K:\anaconda\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [178]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_testset,yKNN)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

# SVM

In [179]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_trainset, y_trainset) 

K:\anaconda\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [180]:
ySVM = clf.predict(X_testset)


In [181]:
print(ySVM[0:5])
print (y_testset [0:5])

['4312' '2134' '2413' '2431' '3142']
0    4321
1    1234
2    2413
3    2431
4    3142
Name: Output, dtype: object


In [182]:
from sklearn.metrics import classification_report
print(classification_report(y_testset,yhat))

              precision    recall  f1-score   support

        1234       0.00      0.00      0.00         1
        1243       0.00      0.00      0.00         0
        2413       1.00      1.00      1.00         1
        2431       1.00      1.00      1.00         1
        3142       1.00      1.00      1.00         1
        3214       1.00      1.00      1.00         1
        3241       1.00      1.00      1.00         1
        4213       1.00      1.00      1.00         1
        4231       1.00      1.00      1.00         1
        4312       1.00      1.00      1.00         1
        4321       0.00      0.00      0.00         1

    accuracy                           0.80        10
   macro avg       0.73      0.73      0.73        10
weighted avg       0.80      0.80      0.80        10



K:\anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
K:\anaconda\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [183]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_testset,ySVM)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

# Rogistics Regression

In [184]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_trainset,y_trainset)
LR

K:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [185]:
yRR = LR.predict(X_testset)

In [186]:
print(yRR[0:5])
print (y_testset [0:5])

['4231' '2134' '2413' '2431' '3142']
0    4321
1    1234
2    2413
3    2431
4    3142
Name: Output, dtype: object


In [187]:
from sklearn.metrics import classification_report
print(classification_report(y_testset,yRR))

              precision    recall  f1-score   support

        1234       0.00      0.00      0.00         1
        2134       0.00      0.00      0.00         0
        2413       1.00      1.00      1.00         1
        2431       1.00      1.00      1.00         1
        3142       1.00      1.00      1.00         1
        3214       1.00      1.00      1.00         1
        3241       1.00      1.00      1.00         1
        4213       1.00      1.00      1.00         1
        4231       0.50      1.00      0.67         1
        4312       1.00      1.00      1.00         1
        4321       0.00      0.00      0.00         1

    accuracy                           0.80        10
   macro avg       0.68      0.73      0.70        10
weighted avg       0.75      0.80      0.77        10



K:\anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
K:\anaconda\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [188]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_testset,yRR)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)